name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prepare API directory structure
        run: |
          mkdir -p dist/api/branches
          cp index.html dist/
          cp source-data/data/banks.json dist/api/
          cp source-data/data/branches/*.json dist/api/branches/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
